export const ui = {
  app: {
    name: "Brainstorm",
    tagline: "Wizualna przestrzeń do debat.",
  },
  nav: {
    discover: "Odkrywaj",
    groups: "Grupy",
    invitations: "Zaproszenia",
  },
  auth: {
    signIn: "Zaloguj się",
    signOut: "Wyloguj",
    account: "Moje konto",
    signInToParticipate: "Zaloguj się, aby uczestniczyć",
    login: {
      title: "Zaloguj się",
      subtitle: "Wróć do swoich dyskusji.",
      emailLabel: "Adres e-mail",
      emailPlaceholder: "ty@example.com",
      passwordLabel: "Hasło",
      passwordPlaceholder: "Twoje hasło",
      submit: "Zaloguj się",
      submitting: "Logowanie…",
      switchPrompt: "Nie masz jeszcze konta?",
      switchAction: "Zarejestruj się",
      invalidCredentials: "Niepoprawny e-mail lub hasło.",
      genericError: "Nie udało się zalogować. Spróbuj ponownie.",
    },
    register: {
      title: "Załóż konto",
      subtitle: "Stwórz miejsce dla swoich debat w kilka sekund.",
      displayNameLabel: "Nazwa wyświetlana",
      displayNamePlaceholder: "np. Ola Kowalska",
      emailLabel: "Adres e-mail",
      emailPlaceholder: "ty@example.com",
      passwordLabel: "Hasło",
      passwordPlaceholder: "Minimum 8 znaków",
      submit: "Załóż konto",
      submitting: "Tworzenie konta…",
      switchPrompt: "Masz już konto?",
      switchAction: "Zaloguj się",
      emailTaken: "Konto z tym adresem e-mail już istnieje.",
      genericError: "Nie udało się utworzyć konta. Spróbuj ponownie.",
    },
    validation: {
      required: "To pole jest wymagane.",
      emailInvalid: "Podaj poprawny adres e-mail.",
      passwordTooShort: "Hasło musi mieć co najmniej 8 znaków.",
      displayNameTooShort: "Nazwa musi mieć co najmniej 2 znaki.",
    },
  },
  dashboard: {
    heroEyebrow: "Publiczne dyskusje",
    heroTitle: "Debatuj, argumentuj, zmieniaj zdania.",
    heroTitleAccent: "zmieniaj zdania.",
    heroSubtitle:
      "Otwarta przestrzeń do głośnego myślenia. Dołącz do rozmowy albo rozpocznij własną.",
    startDebate: "Rozpocznij dyskusję",
    browseFeed: "Przeglądaj feed",
    guestBanner:
      "Przeglądasz jako gość. Możesz czytać każdą publiczną dyskusję, ale dodawanie argumentów wymaga zalogowania.",
    stats: {
      activeDebates: "Aktywne dyskusje",
      participants: "Uczestnicy",
      arguments: "Argumenty",
      votes: "Oddane głosy",
    },
    filters: {
      hottest: "Najpopularniejsze",
      newest: "Najnowsze",
      mostDivisive: "Najbardziej sporne",
    },
    cardOpenParticipate: "Otwórz i dołącz",
    cardManage: "Zarządzaj",
    cardViewReadOnly: "Zobacz (tylko odczyt)",
    loading: "Wczytuję dyskusje…",
    loadFailed: "Nie udało się wczytać dyskusji. Spróbuj odświeżyć stronę.",
    emptyTitle: "Brak publicznych dyskusji",
    emptyBody:
      "Bądź pierwszą osobą, która rozpocznie debatę widoczną dla całej społeczności.",
    emptyCta: "Rozpocznij pierwszą dyskusję",
  },
  sides: {
    pro: "Za",
    against: "Przeciw",
  },
  debates: {
    create: {
      title: "Nowa dyskusja",
      subtitle:
        "Sformułuj tezę i wybierz, kto może w niej uczestniczyć. Dobrze postawiona teza zaprasza do polemiki.",
      thesisLabel: "Teza",
      thesisPlaceholder:
        "np. Praca zdalna na stałe zwiększa produktywność zespołów inżynieryjnych.",
      thesisHint:
        "Od 8 do 280 znaków. Sformułuj jako jedno, klarowne stwierdzenie.",
      visibilityLabel: "Widoczność",
      visibilityPublic: "Publiczna",
      visibilityPublicHint:
        "Dyskusja widoczna dla wszystkich, uczestniczyć mogą zalogowani.",
      visibilityPrivate: "Prywatna",
      visibilityPrivateHint: "Dostępna tylko dla wybranej grupy.",
      visibilityPrivateLocked:
        "Dostępne po utworzeniu lub dołączeniu do grupy (już wkrótce).",
      submit: "Utwórz dyskusję",
      submitting: "Tworzę dyskusję…",
      cancel: "Anuluj",
      genericError: "Nie udało się utworzyć dyskusji. Spróbuj ponownie.",
      thesisTooShort: "Teza musi mieć co najmniej 8 znaków.",
      thesisTooLong: "Teza nie może przekraczać 280 znaków.",
      backToGroup: "Wróć do grupy",
      inGroupEyebrow: "Dyskusja w grupie prywatnej",
      inGroupHint: "Zostanie dodana do",
      groupContextFailed:
        "Nie udało się wczytać grupy. Możesz utworzyć dyskusję publiczną albo wrócić i spróbować ponownie.",
      privateNeedsGroup:
        "Dyskusję prywatną można utworzyć tylko z poziomu wybranej grupy.",
    },
    detail: {
      backToFeed: "Wróć do listy dyskusji",
      authorEyebrow: "Autor",
      privateBadge: "Prywatna",
      publicBadge: "Publiczna",
      argumentsLabel: "Argumenty",
      proLabel: "Za",
      againstLabel: "Przeciw",
      graphLoading: "Wczytuję argumenty…",
      graphLoadFailed: "Nie udało się wczytać argumentów.",
      graphEmptyTitle: "Drzewo argumentów jest puste",
      graphEmptyBody:
        "Rozpocznij debatę - dodaj pierwszy argument Za lub Przeciw tezie.",
      loading: "Wczytuję dyskusję…",
      notFoundTitle: "Nie znaleziono dyskusji",
      notFoundBody:
        "Dyskusja mogła zostać zarchiwizowana albo nigdy nie istniała.",
      forbiddenTitle: "Brak dostępu",
      forbiddenBody:
        "Ta dyskusja jest prywatna. Poproś właściciela grupy o zaproszenie.",
      loadFailed: "Nie udało się wczytać dyskusji.",
      deleteAriaLabel: "Usuń dyskusję",
      deleteConfirm:
        "Na pewno usunąć tę dyskusję? Usunięte zostaną również wszystkie umieszczone w niej argumenty.",
      deleteFailed: "Nie udało się usunąć dyskusji. Spróbuj ponownie.",
    },
    graph: {
      thesisBadge: "Teza",
      aiBadge: "AI",
      addPro: "Dodaj argument Za",
      addAgainst: "Dodaj argument Przeciw",
      selectionHint:
        "Klikasz argument, aby przygotować kontrargument do niego.",
      thesisSelectedHint: "Argument dodajesz bezpośrednio pod tezą.",
      replyingToEyebrow: "Odpowiadasz na",
      changeParent: "Zmień",
      attachToThesis: "Wróć do tezy",
      sentimentPro: "Za przeważa",
      sentimentAgainst: "Przeciw przeważa",
      sentimentControversy: "Sporne",
      sentimentNeutral: "Brak głosów",
      weightAriaLabel: "waga",
      voteWidgetAriaLabel: "Głosy i waga argumentu",
      voteProActive: "Cofnij głos Za",
      voteProInactive: "Zagłosuj Za",
      voteAgainstActive: "Cofnij głos Przeciw",
      voteAgainstInactive: "Zagłosuj Przeciw",
      voteRequiresLogin: "Zaloguj się, aby głosować.",
      voteFailed: "Nie udało się oddać głosu.",
      weightTooltip:
        "Waga argumentu = głosy Za + głosy Przeciw. Każda reakcja zwiększa widoczność - niezależnie od kierunku. Kolor pokazuje dominujący sentyment.",
      deleteAriaLabel: "Usuń argument",
      deleteTooltipCan: "Usuń swój argument",
      deleteTooltipHasChildren:
        "Nie można usunąć argumentu, który ma już odpowiedzi. Najpierw usuń wszystkie odpowiedzi.",
      deleteConfirm: "Na pewno usunąć ten argument?",
      deleteFailed: "Nie udało się usunąć argumentu.",
    },
    argumentForm: {
      panelTitle: "Dodaj argument",
      panelSubtitle:
        "Krótkie, rzeczowe argumenty czyta się najlepiej. Pamiętaj, że Twój głos kształtuje wagę dyskusji.",
      sideLabel: "Strona",
      sidePro: "Za",
      sideAgainst: "Przeciw",
      contentLabel: "Treść argumentu",
      contentPlaceholder:
        "np. Praca zdalna ułatwia rekrutację specjalistów z całego świata, co poszerza pulę talentów.",
      submitPro: "Dodaj argument Za",
      submitAgainst: "Dodaj argument Przeciw",
      submitting: "Dodaję…",
      cancel: "Anuluj",
      requiresLogin:
        "Zaloguj się, aby dodawać argumenty do publicznej dyskusji.",
      signIn: "Zaloguj się",
      contentTooShort: "Argument musi mieć co najmniej 4 znaki.",
      contentTooLong: "Argument nie może przekraczać 2000 znaków.",
      genericError: "Nie udało się dodać argumentu. Spróbuj ponownie.",
      aiToggleLabel: "Wygeneruj przez AI",
      aiModelLabel: "Model",
      aiNoProviders: "Brak dostępnych modeli AI",
      aiGenerateButton: "Generuj",
      aiGenerating: "Generuję…",
      aiGenerateError: "Nie udało się wygenerować argumentu. Spróbuj ponownie.",
      checkingDuplicate: "Sprawdzam duplikaty…",
    },
    ai: {
      lassoToggle: "Zaznacz argumenty",
      lassoCancel: "Anuluj zaznaczenie",
      synthesizeButton: "Streść zaznaczony kontekst",
      synthesisTitle: "Streszczenie zaznaczonego kontekstu",
      synthesisModelLabel: "Model",
      synthesisStart: "Streść zaznaczony kontekst",
      synthesisSending: "Streszczam…",
      synthesisEmpty:
        "Zaznacz argumenty na grafie (lasso), a AI streści wybrany fragment dyskusji.",
      synthesisError:
        "Nie udało się przygotować streszczenia. Spróbuj ponownie.",
      synthesisClose: "Zamknij",
      synthesisAgain: "Streść ponownie",
      summarizeAll: "Streść całą dyskusję",
      synthesisFullTitle: "Streszczenie całej dyskusji",
      summarizeAllSubtitle: "argumentów w dyskusji",
      duplicateTitle: "Podobny argument już istnieje",
      duplicateSubtitle:
        "Wykryto argument o zbliżonym znaczeniu. Możesz wzmocnić istniejący głosem lub dodać swój argument jako nowy niuans.",
      duplicateOriginalLabel: "Istniejący argument",
      duplicateNewLabel: "Twój argument",
      duplicateMerge: "Połącz (dodaj głos)",
      duplicateNuance: "Dodaj jako niuans",
      duplicateMerging: "Łączę…",
    },
  },
  groups: {
    pageTitle: "Grupy prywatne",
    pageSubtitle:
      "Dyskusje zamknięte w gronie zaproszonych osób. Wejdź do grupy, do której należysz, albo utwórz własną.",
    createCta: "Utwórz grupę",
    createFirst: "Utwórz pierwszą grupę",
    ownerBadge: "Właściciel",
    ownerEyebrow: "Właściciel:",
    membersShort: "członków",
    debatesShort: "dyskusji",
    openCta: "Otwórz",
    loading: "Wczytuję grupy…",
    loadFailed:
      "Nie udało się wczytać grup. Odśwież stronę albo spróbuj ponownie za chwilę.",
    emptyTitle: "Nie należysz jeszcze do żadnej grupy",
    emptyBody:
      "Utwórz własną grupę albo poczekaj na zaproszenie - pojawi się w zakładce Zaproszenia.",
    create: {
      title: "Nowa grupa",
      subtitle:
        "Krótka nazwa pomoże członkom rozpoznać grupę na liście dyskusji.",
      nameLabel: "Nazwa grupy",
      namePlaceholder: "np. Zespół projektowy 2026",
      submit: "Utwórz grupę",
      submitting: "Tworzę grupę…",
      nameTooShort: "Nazwa musi mieć co najmniej 3 znaki.",
      nameTooLong: "Nazwa nie może przekraczać 64 znaków.",
      genericError: "Nie udało się utworzyć grupy. Spróbuj ponownie.",
    },
    detail: {
      eyebrow: "Grupa prywatna",
      backToList: "Wróć do listy grup",
      ownedBy: "Założyciel:",
      createdAt: "Utworzono:",
      createDebate: "Utwórz dyskusję w grupie",
      archive: "Usuń grupę",
      confirmArchive:
        "Usunąć grupę? Wszystkie dyskusje wewnątrz zostaną zarchiwizowane.",
      archiveFailed: "Nie udało się usunąć grupy. Spróbuj ponownie.",
      loading: "Wczytuję grupę…",
      notFoundTitle: "Grupa nie istnieje",
      notFoundBody:
        "Grupa mogła zostać usunięta przez właściciela albo nigdy nie istniała.",
      forbiddenTitle: "Brak dostępu",
      forbiddenBody:
        "Nie należysz do tej grupy. Aby zobaczyć jej dyskusje, poproś właściciela o zaproszenie.",
      errorTitle: "Coś poszło nie tak",
      errorBody: "Nie udało się wczytać grupy. Spróbuj odświeżyć stronę.",
      membersTitle: "Członkowie",
      debatesTitle: "Dyskusje w grupie",
      debatesEmpty:
        "W tej grupie nie ma jeszcze dyskusji. Rozpocznij pierwszą i zaproś członków do polemiki.",
      argumentsShort: "argumentów",
      invitationsTitle: "Zaproś użytkownika",
      invitationsSubtitle:
        "Wyszukaj konto po nazwie lub adresie e-mail. Zaproszenie czeka, aż osoba je przyjmie.",
      invitationsListTitle: "Wysłane zaproszenia",
      invitationsListEmpty: "Brak wysłanych zaproszeń.",
      inviteSubmit: "Wyślij zaproszenie",
      inviteSubmitting: "Wysyłam…",
      inviteConflict:
        "Ta osoba ma już oczekujące zaproszenie albo jest członkiem grupy.",
      inviteNoUser: "Wybrane konto nie istnieje.",
      inviteFailed: "Nie udało się wysłać zaproszenia. Spróbuj ponownie.",
    },
  },
  invitations: {
    pageTitle: "Zaproszenia",
    pageSubtitle:
      "Właściciele grup mogą zaprosić Twoje konto do prywatnych dyskusji. Zaproszenie trafia tutaj i wymaga Twojego potwierdzenia.",
    emptyTitle: "Brak oczekujących zaproszeń",
    emptyBody:
      "Gdy ktoś zaprosi Cię do prywatnej grupy, pojawi się to w tym miejscu.",
    goToGroups: "Zobacz moje grupy",
    fromEyebrow: "Zaproszenie do grupy",
    accept: "Przyjmij",
    decline: "Odrzuć",
    responding: "Przetwarzam…",
    respondError:
      "Nie udało się odpowiedzieć na zaproszenie. Spróbuj ponownie.",
    loading: "Wczytuję zaproszenia…",
    loadFailed:
      "Nie udało się wczytać zaproszeń. Odśwież stronę albo spróbuj ponownie za chwilę.",
    status: {
      pending: "Oczekuje",
      accepted: "Przyjęte",
      declined: "Odrzucone",
    },
  },
  users: {
    searchPlaceholder: "Szukaj po nazwie lub adresie e-mail (min. 2 znaki)",
    searching: "Szukam…",
    noResults: "Brak pasujących użytkowników.",
    searchError: "Nie udało się wyszukać użytkowników. Spróbuj ponownie.",
    clearSelection: "Wyczyść wybór",
  },
  common: {
    comingSoon: "W przygotowaniu",
    cancel: "Anuluj",
    close: "Zamknij",
  },
  toast: {
    networkError:
      "Brak połączenia z serwerem. Sprawdź internet i spróbuj ponownie.",
    serverError: "Wystąpił błąd serwera. Spróbuj ponownie za chwilę.",
    forbidden: "Brak dostępu do tego zasobu.",
    notFound: "Nie znaleziono żądanego zasobu.",
    validationError: "Niepoprawne dane. Sprawdź formularz i spróbuj ponownie.",
    rateLimited: "Zbyt wiele żądań. Odczekaj chwilę.",
    unknownError: "Wystąpił nieoczekiwany błąd.",
  },
  theme: {
    toggle: "Przełącz motyw",
    light: "Jasny",
    dark: "Ciemny",
  },
  nav_aria: {
    openMenu: "Otwórz menu",
    closeMenu: "Zamknij menu",
  },
} as const;
